### ISSUE TITLE
.yaml format for C# compilation scheme

### ISSUE THREAD

**Issue by vovapolu** [expload/pravda#247]
I suggest the following `.yaml` format to specify how to compile C# sources for our needs:
```yaml
dotnet-compilation:
  - target: Pravda.dll
    sources:
      - src: PravdaDotNet/Pravda.cs
    optimize: false
  - target: pcall_program.dll
    sources: 
      - src: Pravda.dll
      - src: dotnet-tests/resouces/pcall_program.cs
  - target: pcall.exe
    sources:
       -src: Pravda.dll
       -src: pcall_program.dll
```
